AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Covenant Private School Registration Backend

Globals:
  Function:
    Timeout: 10
    Runtime: python3.14
    Architectures:
      - x86_64
    Environment:
      Variables:
        TABLE_NAME: !Ref RegistrationTable
        ADMIN_SECRET: "CovenantAdmin2027!"
  HttpApi:
    CorsConfiguration:
      AllowOrigins:
        - "*"
      AllowHeaders:
        - "*"
      AllowMethods:
        - "*"

Resources:
  # 1. The Database
  RegistrationTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE

  # 2. The API to Submit Registrations
  RegisterFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.register_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref RegistrationTable
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            Path: /register
            Method: POST

  # 3. The API to View the Dashboard
  GetRegistrationsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.get_registrations_handler
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref RegistrationTable
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            Path: /admin/registrations
            Method: GET

Outputs:
  ApiUrl:
    Description: "Copy this URL to your frontend HTML files!"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com"